# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e87S2fzjCDjxIB_UWD-5SJDtKIFT9-Zi
"""

#Interface leve e descontraida

nome = input("""
   Bem vindo a
=================
SUPER CALCULADORA
=================
Qual o seu nome?

""")

#escolha do primeiro número

num1 = float(input("Digite o primeiro número "))

#escolha da operação. Linguagem que aceita varios simbolos, acessivel memsmo pra quem não entende de programção

operação = input("""Escolha a operação aritméticas
- Soma (+):
- Multiplicação (x ou *):
- Subtração (-):
- Divisão (/):
- Potencia (**):
- Raiz (v):
""").lower()

#escolha do segundo número

num2 = float(input("Digite o segundo número "))

#programção do calculo

operação_valida = True

if operação == "soma" or operação =="+":
  resposta = num1 + num2
elif operação == "mutilplicação"or operação == "x" or operação == "*":
  resposta = num1 * num2
elif operação == "subtração" or operação == "-":
  resposta = num1 - num2
elif operação == "divisão" or operação == "/":
  resposta = num1 / num2
elif operação == "potencia" or operação == "**":
  resposta = num1 ** num2
elif operação == "raiz" or operação == "v":
  resposta = num1 ** (1/num2)

#verificação se a operação foi digitada de maneira correta

else:
  print("Operação não encontrada, por favor tente novamente.")
  operação_valida = False


if operação_valida:
  if resposta % 1 == 0:
    resposta_final = int(resposta)
  else:
    resposta_final = round(resposta, 2)

#resposta final5

if operação_valida:
  print(f"Olá {nome}, a resposta da sua conta é {resposta_final}.")